name: Build
on:
  schedule:
    - cron: '30 5 1 * *'

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]
jobs:
  test:
    name: MSBuild
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.14'

      - name: Build solution for release
        run: msbuild PastDSE.sln -t:rebuild -property:Configuration=Release

      - name: Build solution for debug
        run: msbuild PastDSE.sln -t:rebuild -property:Configuration=Debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: x64
          retention-days: 14
